format = "$all$character"

right_format = """
$rust\
$lua\
$python\
$c\
$cmd_duration
"""

[username]
format = " [â•­â”€]($style)"
show_always = true
style_root = "bold red"
style_user = "fg:#d3859a"


[hostname]
disabled = true
format = "[$hostname]($style) in "
ssh_only = false
style = "fg:#689d69"
trim_at = "-"


[directory]
home_symbol = 'ó°¥³ '#ï€• '
style = "fg:#d3859a"
format = '[ $path]($style) '
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "ó°‰‹ /"


[sudo]
disabled = true


[git_branch]
format = "ó°‡™  [$symbol$branch(:$remote_branch)]($style)"
symbol = "ó°Š¢ "
truncation_length = 4
truncation_symbol = ""
style = "fg:#b8ba25"


[git_status]
format = "[ $untracked$stashed$modified$staged$deleted ]($style)"
untracked = "ó°¡¯ "
stashed = "ó°” "
modified = "ó°€§ " 
staged = "ó°– "
deleted = "ó°…— "
style = "fg:#b4bbc8"


[cmd_duration]
disabled = false
format = "ó±« [$duration]($style)"
min_time = 1


[character]
error_symbol = " [â•°â”€ó±˜ ](bold red)"
success_symbol = ' [â•°â”€ó°‡ ](fg:#8ec07b)'


[package]
disabled = true


[c]
symbol = "C"
format = "[$symbol:($name-$version )]($style)"
version_format = "v${major}.${minor}"


[lua]
symbol = "ó°¢± "
format = "[$symbol:($version )]($style)"
version_format = "v${major}.${minor}"


[dart]
format = "[$symbol:($version )]($style)"
symbol = "î˜ "


[docker_context]
symbol = "ó±¢´ "


[golang]
format = "[$symbol:($version )]($style)"
symbol = "î˜§ "


[nodejs]
format = "[$symbol:($version )]($style)"
symbol = "î‰ "


[python]
format = "[$symbol:($version )]($style)"
symbol = "î˜† "


[rust]
format = "[$symbol:($version )]($style)"
version_format = "v${major}.${minor}"
symbol = "ğŸ¦€"

